# Generated by Django 5.0 on 2026-01-14 08:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_enabled', models.BooleanField(default=True)),
                ('late_fee_grace_days', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_fee_minimum', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('send_rent_reminders', models.BooleanField(default=True)),
                ('reminder_days_before_due', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
