# Generated by Django 5.0 on 2026-01-14 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_utility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='property_photos/')),
                ('photo_type', models.CharField(choices=[('EXTERIOR', 'Exterior'), ('INTERIOR', 'Interior'), ('AMENITY', 'Amenity'), ('UNIT', 'Unit'), ('COMMON_AREA', 'Common Area'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.building')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.unit')),
            ],
            options={
                'verbose_name_plural': 'Property Photos',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
    ]
